// react-frontend/src/App.js
import React, { useEffect, useState, useRef } from 'react';
import axios from 'axios';
import './App.css';

const API_BASE = 'https://zero8-04-2025-datetime.onrender.com/api/time';

const App = () => {
  const [localTime, setLocalTime] = useState('');
  const [selectedTime, setSelectedTime] = useState('');
  const [selectedTimezone, setSelectedTimezone] = useState('');
  const [timezones, setTimezones] = useState([]);
  const selectedTzRef = useRef('');

  useEffect(() => {
    fetchTimezones();
    fetchLocalTime();

    // Fetch time every second
    const interval = setInterval(() => {
      fetchLocalTime();
      if (selectedTzRef.current) {
        fetchSelectedTime(selectedTzRef.current);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const fetchTimezones = async () => {
    try {
      const response = await axios.get(`${API_BASE}/all-timezones`);
      setTimezones(response.data);
      if (response.data.length > 0) {
        const defaultTz = response.data[0];
        setSelectedTimezone(defaultTz);
        selectedTzRef.current = defaultTz;
        fetchSelectedTime(defaultTz);
      }
    } catch (err) {
      console.error('Error fetching timezones:', err);
    }
  };

  const fetchLocalTime = async () => {
    try {
      const response = await axios.get(`${API_BASE}/local`);
      setLocalTime(`${response.data.time} (${response.data.timezone})`);
    } catch (err) {
      console.error('Error fetching local time:', err);
    }
  };

  const fetchSelectedTime = async (tz) => {
    try {
      const response = await axios.get(`${API_BASE}/timezone`, {
        params: { tz }
      });
      setSelectedTime(`${response.data.time} (${response.data.timezone})`);
    } catch (err) {
      setSelectedTime('Invalid timezone selected');
    }
  };

  const handleTimezoneChange = (e) => {
    const newTz = e.target.value;
    setSelectedTimezone(newTz);
    selectedTzRef.current = newTz;
    fetchSelectedTime(newTz);
  };

  return (
    <>
      <div className="container">
        <h2>Local Time</h2>
        <div className="time-block">{localTime}</div>
      </div>

      <div className="container">
        <div className="time-block">
          <h2>Selected Timezone</h2>
          <select value={selectedTimezone} onChange={handleTimezoneChange}>
            {timezones.map((tz) => (
              <option key={tz} value={tz}>{tz}</option>
            ))}
          </select>
          <div className="selected-time">{selectedTime}</div>
        </div>
      </div>
    </>
  );
};

export default App;

// angular-frontend/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  imports: [CommonModule, FormsModule],
})
export class AppComponent implements OnInit, OnDestroy {
  localTime: string = '';
  selectedTime: string = '';
  selectedTimezone: string = '';
  timezones: string[] = [];

  private intervalId: any;
  private apiUrl = 'https://zero8-04-2025-datetime.onrender.com/api/time';

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchTimezones();
    this.fetchLocalTime();

    this.intervalId = setInterval(() => {
      this.fetchLocalTime();
      if (this.selectedTimezone) {
        this.fetchSelectedTime(this.selectedTimezone);
      }
    }, 1000);
  }

  ngOnDestroy(): void {
    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  fetchTimezones(): void {
    this.http.get<string[]>(`${this.apiUrl}/all-timezones`).subscribe({
      next: (zones) => {
        this.timezones = zones;
        if (zones.length > 0) {
          this.selectedTimezone = zones[0];
          this.fetchSelectedTime(this.selectedTimezone);
        }
      },
      error: (err) => console.error('Error fetching timezones:', err),
    });
  }

  fetchLocalTime(): void {
    this.http.get<any>(`${this.apiUrl}/local`).subscribe({
      next: (data) => {
        this.localTime = `${data.time} (${data.timezone})`;
      },
      error: (err) => console.error('Error fetching local time:', err),
    });
  }

  fetchSelectedTime(tz: string): void {
    const params = new HttpParams().set('tz', tz);
    this.http.get<any>(`${this.apiUrl}/timezone`, { params }).subscribe({
      next: (data) => {
        this.selectedTime = `${data.time} (${data.timezone})`;
      },
      error: (err) => {
        this.selectedTime = 'Invalid timezone selected';
      }
    });
  }


  onTimezoneChange(event: Event): void {
    const selectElement = event.target as HTMLSelectElement;
    this.selectedTimezone = selectElement.value;
    this.fetchSelectedTime(this.selectedTimezone);
  }
}
